---
reasoning_llm_options:
  - openai
  - llama

reasoning_llm_model:
  openai:
  - gpt-4o-mini
  - gpt-4o-2024-08-06
  - davinci-002
  - babbage-002
  - gpt-3.5-turbo
  - o1-mini
  - o1-preview

voice_lib_options:
  - openai
  - local

voice_pitch_options: float!

intent_llm_options:
  - openai
  - llama
  - anthropic

intent_llm_model_options:
  - gpt-4o-mini
  - gpt-4o-2024-08-06
  - davinci-002
  - babbage-002

...
